# Generated by Django 4.0.6 on 2022-07-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('testScore', models.FloatField()),
                ('Amount', models.FloatField()),
                ('ari', models.FloatField()),
            ],
        ),
    ]
