# Generated by Django 4.0.6 on 2022-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvAPP', '0003_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enter',
            field=models.FloatField(null=True),
        ),
    ]
