# Generated by Django 4.0.6 on 2022-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvAPP', '0004_student_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
